### ISSUE TITLE
[QHD合同上线] 1.1 服务器安装

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-contracts-app#14]
- [x] 应用服务器：141服务器
- [x] 数据库服务器：即 OA系统数据库服务器，无需单独再部署 
- [x] 确认系统可访问
- [x] 落实附件备份机制：每个半点备份一次

**Comment by chenzhipei** [comment]
服务部署路径：/srv/git/steedos-project-qhd
起服务：docker-compose up -d
停服务：docker-compose stop
