### ISSUE TITLE
[QHD合同上线] 2.1 历史数据导入：数据库记录

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-contracts-app#17]
老合同系统
- [x] 2019年
- [x] 2018年
- [x] 2017年
- [x] 2016年
- [x] 2015年
- [x] 2014年
- [x] 2013年
- [x] 2012年
- [x] 2011年
- [x] 2010年
- [x] 无签订日期
- [x] 切换期间遗漏的（老合同中有、新合同中无）
- [ ] 老系统就已遗漏的（20190920之前的）

**Comment by marchtian** [comment]
[合同涉及部室单位.xlsx](https://github.com/steedos/steedos-contracts-app/files/3554831/default.xlsx)

**Comment by marchtian** [comment]
[合同涉及部室单位.xlsx](https://github.com/steedos/steedos-contracts-app/files/3583284/default.xlsx)

**Comment by marchtian** [comment]
0921-0922 已导入：2019年、2018年

**Comment by marchtian** [comment]
0923 已导入：2017年

**Comment by chenzhipei** [comment]
0923已导入2016、2015、2014数据

**Comment by chenzhipei** [comment]
1008导入2013年台账数据

**Comment by chenzhipei** [comment]
导入切换期间遗漏的记录及附件

**Comment by chenzhipei** [comment]
20191017导入2012年数据

**Comment by chenzhipei** [comment]
20191018导入2011及之前的数据，导入签订日期为空的数据
