### ISSUE TITLE
[QHD合同上线] 2.3 历史数据导入：老OA的合同审批单生成html作为附件挂入新合同台账记录

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-contracts-app#23]
- [x] 给4个合同审批单编写chrome规范下的html模板
- [ ] 脚本，从老OA按模板生成html并导入到新合同系统

**Comment by baozhoutao** [comment]
旧OA申请单显示支持chrome，更改文件：
1 qgbg\modules\workflow\dbflow_table_grab.jsp
2 qgbg\elements\excludes\workflow_grabfile.jsp

**Comment by baozhoutao** [comment]
请读取旧OA系统的这个接口获取审批单的html: /qgbg/elements/excludes/workflow_grabfile.jsp?FileID=申请单id
