### ISSUE TITLE
新建图片签名报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-contracts-app#31]
![image](https://user-images.githubusercontent.com/26241897/69472322-9498ca80-0de3-11ea-9864-3d007e0b5f9d.png)

**Comment by yinlianghui** [comment]
- 该问题是因为工作区未付费造成的，执行相关数据库脚本，即可正常使用了。
- 因space_user_signs对象的user字段设置为is_name会有些bug，比如列表没法点击进入详细、详细界面顶部显示异常，所以去掉了is_name属性
