### ISSUE TITLE
新建页面视图后数据不展示

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-contracts-app#34]
![image](https://user-images.githubusercontent.com/26241897/69476449-0b9a8700-0e15-11ea-8b1c-94a826568fb2.png)
![image](https://user-images.githubusercontent.com/26241897/69476461-3258bd80-0e15-11ea-8b59-d5f6b75c4c9d.png)

**Comment by yinlianghui** [comment]
只有组织机构中新建视图才有问题，而且新建视图时显示列中有“上级组织”时才有该问题

**Comment by yinlianghui** [comment]
该问题出现的条件比较极端，不处理
