### ISSUE TITLE
合同-首页 点击“查看全部”进入到了404页面

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-contracts-app#39]
可能是配置了ROOTURL出的问题
<img width="670" alt="image" src="https://user-images.githubusercontent.com/6219465/74499242-0f264180-4f1e-11ea-873a-5e5afe980a43.png">

**Comment by yinlianghui** [comment]
<img width="286" alt="image" src="https://user-images.githubusercontent.com/6219465/74586279-f2266700-5020-11ea-9707-ca8c0ca477a5.png">

**Comment by yinlianghui** [comment]
已修正，但是新版本安装不上，等网络好的时候升级到`@steedos/react@1.14.10`就行了
